#!/bin/bash
if [read -s -p '.png'];then
echo"$ls *.png| wc -l"
fi
if [read -s -p '.txt'];then
echo"$ls *.txt| wc -1"
fi
if [read -s -p '.pdf'];then
echo"$ls *.pdf| wc -1"
fi
if [read -s -p] '.py'];then
echo"$ls *.py| wc -1"
fi
if [read -s -p '.etc']; then
echo "$ls *.etc| wc -1"
fi


